unused/flask_projects/oleg/app/models.py
from app import db
from datetime import datetime
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', str(s))

post_tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)

roles_users = db.Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text())
    created = db.Column(db.DateTime, default=datetime.now)
    tags = db.relationship('Tag',
                            secondary=post_tags,
                            backref=db.backref('posts'),
                            lazy='dynamic')

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}'.format(self.id, self.title)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))
    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)
    def __repr__(self):
        return '<Tag id: {}, name: {}'.format(self.id, self.name)

# class User(db.Model):
#     pass

unused/flask_projects/oleg/app/posts/forms.py
from wtforms import Form, StringField, TextAreaField
from flask_wtf import FlaskForm

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

unused/flask_projects/oleg/app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore, Security

app = Flask(__name__)
app.config.from_object(Configuration)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db',MigrateCommand)

from models import *
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

unused/flask_projects/oleg/app/main.py
from app import app, db

from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run(port=5000, debug=True)

unused/flask_projects/oleg/app/posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models import *
from .forms import *
from app import db
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST','GET'])
@login_required
def post_create():
    form = PostForm()
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('sdfsdf')
        else:
            return redirect(url_for('posts.index'))
    return render_template('posts/post_create.html', form=form)

@posts.route('/<slug>/post_update/', methods=['GET','POST'])
@login_required
def post_update(slug):
    post = Post.query.filter(Post.slug==slug).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        # post.title = request.form[('title')]
        # post.body = request.form[('body')]
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/post_update.html', post=post, form=form)

@posts.route('/')
@login_required
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if q:
        posts = Post.query.filter(Post.title.contains(q)|Post.body.contains(q)).all()
    else:
        posts = Post.query.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=3)
    return render_template('posts/index.html', posts=posts, pages=pages)

@posts.route('/<slug>')
@login_required
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html',tags=tags, post=post)

@posts.route('/tag/<slug>')
@login_required
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    post = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, post=post)

unused/flask_projects/oleg/app/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    blueprint index page
{% endblock %}
{% block content_title %}
    Posts
{% endblock %}
{%block content%}
    {%for post in posts%}
         <p>
             <a href = "{{ url_for('posts.post_detail', slug=post.slug)}}">
                {{post.title}}
             </a>
         </p>
     {%endfor%}
     <nav>
         <ul class='paginator'>
             <li class='disabled'>
                 <a href="" aria-label='Previous'>
                     <span aria-hidden="true">
                         &laquo;
                     </span>
                 </a>
             </li>
             <li class='active'>
                 <a href="" aria-label='Previous'>
                     <span clas="sr-only" aria-hidden="true">
                         (current)
                     </span>
                 </a>
             </li>
         </ul>
     </nav>
{%endblock%}

unused/flask_projects/oleg/app/posts/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
    Creat new post
{% endblock %}
{% block content_title %}
    New Post
{% endblock %}
{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('posts.post_create')}}" method="post">
            {{form.hidden_tag}}
            {% for field in form %}
                <div class="form-group">
                    <p>{{field.label(class='control-label')}}</p>
                    <p>{{field(class='form-control')}}</p>
                </div>
            {% endfor %}
            <button type="submit" class='btn btn-success'>Create</button>
        </form>
    </div>

{% endblock %}

unused/flask_projects/oleg/app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    {{post.title}}
{% endblock %}
{% block content_title %}
    {{post.title}}
{% endblock %}
{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <span class="label label-primary">{{tag.name}}</span>
        {% endfor %}
    </div>
    {{post.body}}
{% endblock %}

unused/flask_projects/oleg/app/posts/templates/posts/post_update.html
{% extends 'base.html' %}
{% block title %}
     Udate post
{% endblock %}
{% block content_title %}
     Post Update
{% endblock %}
{% block content %}
    <div class="col-md-6">
        <form action="{{url_for('posts.post_update', slug=post.slug)}}" method="post">
            {% for field in form %}
                <div class="form-group">
                    <p>{{field.label(class='control-label')}}</p>
                    <p>{{field(class='form-control')}}</p>
                </div>
            {% endfor %}
            <button type="submit" class='btn btn-success'>Update</button>
        </form>
    </div>

{% endblock %}

unused/flask_projects/oleg/app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}
{% block title %}
    {{tag.nage}} posts
{% endblock %}
{% block content_title %}
    Posts for '{{tag.name}}' tag:
{% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
        </div>
    {% endfor %}
{% endblock %}