unused/flask_projects/tceh/rest_api22/djago_api/djago_api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from study import urls as study_urls
from rest_api import urls as rest_urls
from get_from_api import urls as api_get


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')),

    url(r'^', include(study_urls, namespace='study')),

    url(r'^api/v1/', include(rest_urls, namespace="rest_api")),
    url(r'^get/v1', include(api_get, namespace='api_get')),

]

unused/flask_projects/tceh/rest_api22/djago_api/study/urls.py
from django.conf.urls import url

from study.views import index, lessons, lesson, themes, theme

urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^lessons/$', lessons, name='lessons'),
    url(r'^lessons/(?P<lesson_pk>[0-9]+)/', lesson, name='lesson'),

    url(r'^themes/$', themes, name='themes'),
    url(r'^themes/(?P<theme_pk>[0-9]+)/', theme, name='theme'),
]

unused/flask_projects/tceh/rest_api22/djago_api/study/models.py
from __future__ import unicode_literals

from django.db import models


class Lesson(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=40)

    def __unicode__(self):
        return "Lesson number %s (%s)" % (self.number, self.title)


class Theme(models.Model):
    name = models.CharField(max_length=35)
    description = models.TextField()
    lesson = models.ForeignKey('Lesson', related_name='theme', blank=True,
                               null=True)

    def __unicode__(self):
        return "Theme: %s" % self.name

unused/flask_projects/tceh/rest_api22/djago_api/study/forms.py
from django import forms
from django.core.exceptions import ValidationError
import pdb

from study.models import Lesson, Theme


class PlaceholderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlaceholderForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                if type(field.widget) in (forms.TextInput, ):
                    field.widget.attrs.update(
                        {'placeholder': field.label, 'class': 'span10'}
                    )
                if type(field.widget) in (forms.Select, ):
                    field.widget.attrs.update({'class': 'span10'})
                    field.empty_label = field.label

    def as_p(self):
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True
        )


class LessonForm(PlaceholderForm):
    class Meta:
        model = Lesson
        fields = ['number', 'title']

    def clean(self):
        data = self.cleaned_data

        # If we changing already existing lesson
        if self.instance.pk:
            return data

        existing_lessons_id = [lesson.number for lesson in Lesson.objects.all()]

        if data['number'] in existing_lessons_id:
            raise ValidationError('You must enter unique lesson number!',
                                  code='invalid')

        return data


class ThemeForm(PlaceholderForm):
    class Meta:
        model = Theme
        fields = ['name', 'description', 'lesson']

unused/flask_projects/tceh/rest_api22/djago_api/study/views.py
from django.shortcuts import render
from django.db import transaction
from django.http import Http404

from study.forms import LessonForm, ThemeForm
from study.models import Lesson, Theme

import pdb

def index(request):
    return render(request, 'study/index.html')


def lessons(request):
    lesson_form = LessonForm(
        initial={'number': Lesson.objects.last().number + 1}
    )

    if request.method == 'POST':
        previous_lesson_form = LessonForm(request.POST)
        if previous_lesson_form.is_valid():
            with transaction.atomic():
                previous_lesson_form.save()
            lesson_form.initial['number'] += 1
        else:
            lesson_form = previous_lesson_form

    return render(request, 'study/lessons.html', {
        'lessons': Lesson.objects.all(),
        'form': lesson_form,
    })


def lesson(request, lesson_pk):
    try:
        lesson_form = LessonForm(instance=Lesson.objects.get(pk=lesson_pk))
    except Lesson.DoesNotExist:
        raise Http404('There in no such lesson!')

    if request.method == 'POST':
        instance = Lesson.objects.get(pk=lesson_pk)
        previous_lesson_form = LessonForm(request.POST, instance=instance)
        if previous_lesson_form.is_valid():
            with transaction.atomic():
                previous_lesson_form.save()
            lesson_form = previous_lesson_form

    return render(request, 'study/lesson.html', {
        'form': lesson_form,
        'themes': Lesson.objects.get(pk=lesson_pk).theme.all(),
    })


def themes(request):
    theme_form = ThemeForm()

    if request.method == 'POST':
        previous_theme_form = ThemeForm(request.POST)
        if previous_theme_form.is_valid():
            with transaction.atomic():
                previous_theme_form.save()
        else:
            theme_form = previous_theme_form

    return render(request, 'study/themes.html', {
        'themes': Theme.objects.all(),
        'form': theme_form,
    })


def theme(request, theme_pk):
    try:
        theme_form = ThemeForm(instance=Theme.objects.get(pk=theme_pk))
    except Theme.DoesNotExist:
        raise Http404('There in no such lesson theme!')

    if request.method == 'POST':
        instance = Theme.objects.get(pk=theme_pk)
        previous_theme_form = ThemeForm(request.POST, instance=instance)
        if previous_theme_form.is_valid():
            with transaction.atomic():
                previous_theme_form.save()
            theme_form = previous_theme_form

    return render(request, 'study/theme.html', {
        'form': theme_form,
    })

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'custom.css' %}" />

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="{% url 'study:index' %}">Home</a></li>
              <li><a href="{% url 'study:lessons' %}">Lessons</a></li>
              <li><a href="{% url 'study:themes' %}">Themes</a></li>
              <li><a href="{% url 'rest_api:api-root' %}">REST API</a></li>
              <li><a href="{% url 'api_get:index' %}">Get from api</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% block content %}{% endblock content %}
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/index.html
{% extends 'study/_base.html' %}

{% block title %}Django API{% endblock title %}

{% block content %}
    <h1>Welcome to Djago API!</h1>

    <p>Checkout lessons and themes here :).</p>
{% endblock content %}

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/lesson.html
{% extends 'study/_base.html' %}

{% block title %}Django API: lesson {{ lesson.number }}{% endblock title %}

{% block content %}

    <h1>Lesson</h1><br>

    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            {{ field.label_tag }}<br>
            {{ field }}<br>
            {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <br>
    <h3>Themes for lesson:</h3>
    {% if themes %}
        {% for theme in themes %}
            <a href="{% url 'study:theme' theme.pk %}">{{ theme }}</a></br>
        {% endfor %}
    {% else %}
        Now there are no themes for this lesson :(.
    {% endif %}
{% endblock content %}

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/lessons.html
{% extends 'study/_base.html' %}

{% block title %}Django API: lesson{% endblock title %}

{% block content %}
    <h1>Lessons page</h1>

    <br></b><h3>Available lessons:</h3>
    {% for lesson in lessons %}
        <p><a href="{% url 'study:lesson' lesson.pk %}">{{ lesson }}</a></p>
    {% endfor %}

    <br><h3>New lesson:</h3>
    <form action="{% url 'study:lessons' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/theme.html
{% extends 'study/_base.html' %}

{% block title %}Django API: {{ theme.name }}{% endblock title %}

{% block content %}

    <h1>Lesson theme</h1><br>

    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            {{ field.label_tag }}<br>
            {{ field }}<br>
            {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

unused/flask_projects/tceh/rest_api22/djago_api/study/templates/study/themes.html
{% extends 'study/_base.html' %}

{% block title %}Django API: themes{% endblock title %}

{% block content %}
    <h1>Lesson themes</h1>

    <br></b><h3>Available lessons themes:</h3>
    {% for theme in themes %}
        <p><a href="{% url 'study:theme' theme.pk %}">{{ theme }}</a></p>
    {% endfor %}

    <br><h3>New lesson theme:</h3>
    <form action="{% url 'study:themes' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}